apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: "{{ .Values.alertmanager.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  hosts:
    - "{{ .Values.alertmanager.host }}"
  gateways:
    - "{{ .Values.gateway }}"
  http:
    - route:
        - destination:
            host: "{{ .Values.alertmanager.destination }}"
            port:
              number: {{ .Values.alertmanager.port }}
