apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: astronomer-gateway-tls
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        mode: SIMPLE
        credentialName: astronomer-tls
