apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.grafana.host }}
  gateways:
    - {{ .Values.gateway }}
  http:
    - route:
        - destination:
            host: {{ .Values.grafana.destination }}
            port:
              number: {{ .Values.grafana.port }}
