apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.public.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.public.host1 }}
    - {{ .Values.public.host2 }}
  gateways:
    - {{ .Values.gateway }}
  http:
    - route:
        - destination:
            host: {{ .Values.public.destination }}
            port:
              number: {{ .Values.public.port }}

